# Generated by Django 3.1.2 on 2020-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
