# Generated by Django 3.1.2 on 2020-11-11 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_Listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
