# Generated by Django 3.1.2 on 2020-11-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
